#include <stdexcept>

int main()
{
    throw std::runtime_error("Test");
    return 0;
}
